"""FASE-REPORTES-S3-COMISION: comision de plataforma por pedido

Revision ID: 09440fc6b1f2
Revises: d307d1196c18
Create Date: 2026-09-03 15:36:00.438771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09440fc6b1f2'
down_revision = 'd307d1196c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comision_plataforma', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('comision_plataforma')

    # ### end Alembic commands ###
