"""FASE-MELI-S1-FIX: el scope de la credencial es Text, no varchar(255)

Revision ID: 418ecc984913
Revises: 4b0c77a8c3cd
Create Date: 2026-09-04 19:53:21.264340

El callback de Mercado Libre autorizaba bien y despues reventaba al hacer
commit, con StringDataRightTruncation sobre varchar(255). La columna que se
quedaba corta NO era ninguna de las cifradas -- `access_token_cifrado` y
`refresh_token_cifrado` ya son Text desde FASE2-S1 y aguantan de sobra
(Fernet infla ~1.45x: un token de 1000 caracteres da 1464) -- sino `scope`,
que guarda texto plano y era la unica varchar(255) que quedaba en la tabla.

El scope lo escribe el proveedor, no nosotros: Mercado Libre devuelve la
lista de permisos concedidos y no hay numero mas grande que sea "seguro"
manana. Por eso Text y no varchar(512): un campo informativo no puede ser el
que decide si una integracion funciona.

Tiendanube tenia el mismo riesgo latente en la misma columna (hoy guarda 55
caracteres, sin margen garantizado), y se corrige con esto.

OJO con el downgrade: si para entonces hay un scope de mas de 255 caracteres
guardado, Postgres rechaza el ALTER en vez de truncar en silencio. Es lo
deseable -- volver atras tiene que doler si hay datos que no entran -- pero
hay que saberlo antes de correrlo.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418ecc984913'
down_revision = '4b0c77a8c3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial_canal', schema=None) as batch_op:
        batch_op.alter_column('scope',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial_canal', schema=None) as batch_op:
        batch_op.alter_column('scope',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
