"""FASE2-S1 modelo ecommerce

Revision ID: 4a3c449fc7b6
Revises: dfd89229795b
Create Date: 2026-09-01 13:04:54.459912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3c449fc7b6'
down_revision = 'dfd89229795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneda_origen', sa.String(length=3), nullable=False),
    sa.Column('moneda_destino', sa.String(length=3), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tasa', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda_origen', 'moneda_destino', 'fecha', name='uq_tipo_cambio_par_fecha')
    )
    with op.batch_alter_table('tipo_cambio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipo_cambio_fecha'), ['fecha'], unique=False)

    op.create_table('canal_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_tienda_externo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', name='uq_canal_venta_empresa_tipo')
    )
    with op.batch_alter_table('canal_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canal_venta_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('cuenta_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('metodo_ingesta', sa.String(length=20), server_default='api', nullable=False),
    sa.Column('identificador_externo', sa.String(length=100), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('saldo_actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_sync', sa.DateTime(), nullable=True),
    sa.CheckConstraint("metodo_ingesta = 'api'", name='ck_cuenta_cobro_metodo_ingesta_api'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_cuenta_cobro_empresa_nombre')
    )
    with op.batch_alter_table('cuenta_cobro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuenta_cobro_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sku', name='uq_producto_empresa_sku')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('credencial_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('tipo_credencial', sa.String(length=30), nullable=False),
    sa.Column('access_token_cifrado', sa.Text(), nullable=True),
    sa.Column('refresh_token_cifrado', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credencial_canal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credencial_canal_canal_id'), ['canal_id'], unique=False)

    op.create_table('liquidacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=False),
    sa.Column('procesador', sa.String(length=30), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('fecha_liquidacion', sa.Date(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('monto_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comisiones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retenciones', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuenta_cobro.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procesador', 'id_externo', name='uq_liquidacion_procesador_id_externo')
    )
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidacion_cuenta_cobro_id'), ['cuenta_cobro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacion_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidacion_fecha_liquidacion'), ['fecha_liquidacion'], unique=False)

    op.create_table('mapeo_producto_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('id_producto_externo', sa.String(length=100), nullable=False),
    sa.Column('id_variante_externo', sa.String(length=100), server_default='', nullable=False),
    sa.Column('sku_externo', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal_venta.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canal_id', 'id_producto_externo', 'id_variante_externo', name='uq_mapeo_canal_producto_variante')
    )
    with op.batch_alter_table('mapeo_producto_canal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapeo_producto_canal_canal_id'), ['canal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapeo_producto_canal_producto_id'), ['producto_id'], unique=False)

    op.create_table('movimiento_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_posterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id_externo_procesador', sa.String(length=120), nullable=True),
    sa.Column('hash_dedup', sa.String(length=64), nullable=False),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta_cobro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'id_externo_procesador', name='uq_movimiento_cuenta_id_externo'),
    sa.UniqueConstraint('hash_dedup')
    )
    with op.batch_alter_table('movimiento_cuenta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_cuenta_cuenta_id'), ['cuenta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_cuenta_fecha'), ['fecha'], unique=False)

    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=False),
    sa.Column('numero_externo', sa.String(length=50), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('estado_externo', sa.String(length=50), nullable=True),
    sa.Column('comprador_nombre', sa.String(length=150), nullable=True),
    sa.Column('comprador_email', sa.String(length=150), nullable=True),
    sa.Column('comprador_doc', sa.String(length=30), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_descuentos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_envio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fecha_sync', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal_venta.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canal_id', 'id_externo', name='uq_pedido_canal_id_externo')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_canal_id'), ['canal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_fecha_pedido'), ['fecha_pedido'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=True),
    sa.Column('entidad', sa.String(length=30), nullable=False),
    sa.Column('operacion', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cursor_desde', sa.DateTime(), nullable=True),
    sa.Column('cursor_hasta', sa.DateTime(), nullable=True),
    sa.Column('registros_leidos', sa.Integer(), nullable=False),
    sa.Column('registros_nuevos', sa.Integer(), nullable=False),
    sa.Column('registros_actualizados', sa.Integer(), nullable=False),
    sa.Column('registros_error', sa.Integer(), nullable=False),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal_venta.id'], ),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuenta_cobro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_log_canal_id'), ['canal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_log_cuenta_cobro_id'), ['cuenta_cobro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_log_fecha_inicio'), ['fecha_inicio'], unique=False)

    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_cobro_id', sa.Integer(), nullable=True),
    sa.Column('liquidacion_id', sa.Integer(), nullable=True),
    sa.Column('procesador', sa.String(length=30), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('cuotas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('monto_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comision', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('fecha_acreditacion', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canal_id'], ['canal_venta.id'], ),
    sa.ForeignKeyConstraint(['cuenta_cobro_id'], ['cuenta_cobro.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procesador', 'id_externo', name='uq_pago_procesador_id_externo')
    )
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pago_canal_id'), ['canal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_cuenta_cobro_id'), ['cuenta_cobro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_fecha_pago'), ['fecha_pago'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_liquidacion_id'), ['liquidacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pago_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('sku_externo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('costo_unitario_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_item_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_item_producto_id'), ['producto_id'], unique=False)

    op.create_table('regla_categorizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('campo', sa.String(length=30), nullable=False),
    sa.Column('operador', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('tipo_destino', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regla_categorizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regla_categorizacion_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regla_categorizacion_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('conciliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_conciliacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento_cuenta.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id', 'movimiento_id', name='uq_conciliacion_pago_movimiento')
    )
    with op.batch_alter_table('conciliacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conciliacion_movimiento_id'), ['movimiento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conciliacion_pago_id'), ['pago_id'], unique=False)

    op.create_table('devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('evento_previo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comision_devuelta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_previo_id'], ['devolucion.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devolucion_evento_previo_id'), ['evento_previo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devolucion_fecha_evento'), ['fecha_evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_devolucion_id_externo'), ['id_externo'], unique=False)
        batch_op.create_index(batch_op.f('ix_devolucion_pago_id'), ['pago_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devolucion_pedido_id'), ['pedido_id'], unique=False)

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cuenta_pago_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comprobante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deducible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('moneda', sa.String(length=3), nullable=True))
        batch_op.create_foreign_key('fk_gasto_cuenta_pago_id', 'cuenta_cobro', ['cuenta_pago_id'], ['id'])

    # ### end Alembic commands ###

    # --- Semilla: ancla de canales para la Fase 3 ---------------------------
    # Dos filas por empresa, ambas activo=False porque todavia no hay
    # credenciales cargadas. Existir vacias es el punto: cuando Fase 3 conecte
    # Tiendanube o Mercado Libre ya tiene a que colgar la credencial, en vez de
    # tener que crear el canal sobre la marcha.
    conn = op.get_bind()
    conn.execute(sa.text("""
        INSERT INTO canal_venta (empresa_id, tipo, nombre, activo, fecha_creacion)
        SELECT e.id, c.tipo, c.nombre, false, now()
        FROM empresa e
        CROSS JOIN (VALUES
            ('tiendanube', 'Tiendanube'),
            ('mercadolibre', 'Mercado Libre')
        ) AS c(tipo, nombre)
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gasto_cuenta_pago_id', type_='foreignkey')
        batch_op.drop_column('moneda')
        batch_op.drop_column('deducible')
        batch_op.drop_column('comprobante')
        batch_op.drop_column('cuenta_pago_id')
        batch_op.drop_column('proveedor')

    with op.batch_alter_table('devolucion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devolucion_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_devolucion_pago_id'))
        batch_op.drop_index(batch_op.f('ix_devolucion_id_externo'))
        batch_op.drop_index(batch_op.f('ix_devolucion_fecha_evento'))
        batch_op.drop_index(batch_op.f('ix_devolucion_evento_previo_id'))

    op.drop_table('devolucion')
    with op.batch_alter_table('conciliacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conciliacion_pago_id'))
        batch_op.drop_index(batch_op.f('ix_conciliacion_movimiento_id'))

    op.drop_table('conciliacion')
    with op.batch_alter_table('regla_categorizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regla_categorizacion_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_regla_categorizacion_categoria_id'))

    op.drop_table('regla_categorizacion')
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_item_producto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_item_pedido_id'))

    op.drop_table('pedido_item')
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pago_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pago_liquidacion_id'))
        batch_op.drop_index(batch_op.f('ix_pago_fecha_pago'))
        batch_op.drop_index(batch_op.f('ix_pago_cuenta_cobro_id'))
        batch_op.drop_index(batch_op.f('ix_pago_canal_id'))

    op.drop_table('pago')
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_log_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_sync_log_cuenta_cobro_id'))
        batch_op.drop_index(batch_op.f('ix_sync_log_canal_id'))

    op.drop_table('sync_log')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_fecha_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedido_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_canal_id'))

    op.drop_table('pedido')
    with op.batch_alter_table('movimiento_cuenta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_cuenta_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimiento_cuenta_cuenta_id'))

    op.drop_table('movimiento_cuenta')
    with op.batch_alter_table('mapeo_producto_canal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapeo_producto_canal_producto_id'))
        batch_op.drop_index(batch_op.f('ix_mapeo_producto_canal_canal_id'))

    op.drop_table('mapeo_producto_canal')
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidacion_fecha_liquidacion'))
        batch_op.drop_index(batch_op.f('ix_liquidacion_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_liquidacion_cuenta_cobro_id'))

    op.drop_table('liquidacion')
    with op.batch_alter_table('credencial_canal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credencial_canal_canal_id'))

    op.drop_table('credencial_canal')
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_empresa_id'))

    op.drop_table('producto')
    with op.batch_alter_table('cuenta_cobro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuenta_cobro_empresa_id'))

    op.drop_table('cuenta_cobro')
    with op.batch_alter_table('canal_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canal_venta_empresa_id'))

    op.drop_table('canal_venta')
    with op.batch_alter_table('tipo_cambio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipo_cambio_fecha'))

    op.drop_table('tipo_cambio')
    # ### end Alembic commands ###
