"""FASE-REPORTES-S3-ENVIO-VENDEDOR: costo de envio que paga el vendedor

Revision ID: d307d1196c18
Revises: 5d10e8d6bd8c
Create Date: 2026-09-03 14:01:15.072715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd307d1196c18'
down_revision = '5d10e8d6bd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_envio_vendedor', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('costo_envio_vendedor')

    # ### end Alembic commands ###
